# 0?? ???? ???? ??? ????? ????.
server:
  port: 0

spring:
  application:
    name: user-service
# eureka.instance.instance-id? ?????? Eureka ????? ?? ????? ????. default? ??? ????.
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    # fetch-registry? Eureka ????? ?????? ??? ????? ??? ???? ???? ????.
    # true? ????, ??? ??? ???? ????.
    fetch-registry: true
    # service-url.defaultZone? ??? ????? ???? ???????.
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka